"""Unit tests for the CWM layer: sandbox, reference model, test generation,
synthesis, refinement, inference, value selection, arena, reporting.

Every LLM-dependent path runs against ``RecordedClient`` fixtures committed
under ``fixtures/``, hand-authored plausible synthesised model source, not
real API output. A test that needed a live call would be a broken test.

The fixture files are regenerated by replaying the exact flows below through
``RecordingClient``; the prompt hashes therefore match what these tests
produce, and a ``FixtureMiss`` here means the fixtures and the prompts have
drifted apart and must be re-recorded.
"""

from __future__ import annotations

import random
import types
from dataclasses import asdict
from pathlib import Path

import pytest

from fronts.cwm.arena import ArenaConfig, play_episode
from fronts.cwm.arena import run as arena_run
from fronts.cwm.inference import (
    FallbackInference,
    inference_accuracy,
    load_state_inference,
    synthesise_state_inference,
    synthesise_state_inference_source,
    validate_history,
)
from fronts.cwm.llm import (
    FixtureMiss,
    RecordedClient,
    RecordingClient,
    extract_code,
    prompt_key,
)
from fronts.cwm.reference import ReferenceConfig, ReferenceWorldModel
from fronts.cwm.refine import RefineConfig, RefinementNode, RefinementTree
from fronts.cwm.refine import refine as refine_tree
from fronts.cwm.report import ModelQualityReport
from fronts.cwm.sandbox import (
    CWM_METHOD_PARAMS,
    ProtocolViolation,
    Sandbox,
    SandboxConfig,
    SandboxTimeout,
    SandboxViolation,
    call_with_timeout,
    check_protocol_methods,
    instantiate,
)
from fronts.cwm.synth import SynthConfig, build_prompt, synthesise
from fronts.cwm.tests_from_traj import (
    LEGALITY,
    NO_CRASH,
    OBSERVATION_RECONSTRUCTION,
    TERMINATION,
    TRANSITION,
    ModelTest,
    Tolerance,
    generate,
    replay,
    split,
)
from fronts.game.action_space import ActionCodec
from fronts.game.types import (
    TERMINAL_PLAYER,
    Archetype,
    ClaimClass,
    CtaMode,
    EmotionalVector,
    Format,
    Hold,
    HookFamily,
    Observation,
    Platform,
    Publish,
    SemanticTier,
    Step,
    Trajectory,
)
from fronts.protocols import CodeWorldModel

pytestmark = pytest.mark.unit

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"

RULES_TEXT = (
    "Organic distribution over a 30-day horizon. Each day the operator "
    "publishes one item, scales an angle, kills an angle, or holds. The "
    "platform ranks content by a hidden weighting over hook rate, hold "
    "rate, saves, shares and comments; repeated use of the same "
    "archetype-angle pair fatigues; observations arrive 24-72h late with "
    "attribution coverage below 1."
)

ACTION_A = (
    "publish|tiktok|carousel|anti_hero_rant|anger_injustice|tribal_identity|"
    "pattern_interrupt|avatar=solo_founder|cta=start_trial|"
    "claim=first_party_proof|angle=launch_theater|utm=c0412"
)
ACTION_B = (
    "publish|x|text_thread|ugc_review|aspiration_status|generic_slop|"
    "curiosity_gap|avatar=agency_ops|cta=reply_keyword|claim=mechanism|"
    "angle=enemy_of_slop|utm=c07e33"
)

# Two hand-authored "synthesised" candidates. V1 loads and satisfies the
# protocol but its legal-action list omits the recorded moves; V2 is the
# refinement that fixes that. Pure stdlib, no dunder access, the
# same constraints a real synthesised module faces in the sandbox.
V1_SOURCE = '''\
"""Candidate world model: reach decays with repetition, conversions follow reach."""

HORIZON = 30


class Obs:
    def __init__(self, utm_content, reach, hook_rate, conversions):
        self.utm_content = utm_content
        self.impressions = int(reach * 2)
        self.reach = int(reach)
        self.hook_rate = hook_rate
        self.hold_rate = hook_rate * 0.7
        self.saves = int(reach * 0.01)
        self.shares = int(reach * 0.008)
        self.comments = int(reach * 0.006)
        self.profile_visits = int(reach * 0.01)
        self.link_clicks = int(reach * 0.002)
        self.attributed_conversions = conversions
        self.attribution_coverage = 0.72
        self.incrementality = 0.77
        self.is_partial = False
        self.dark_social_estimate = 0.65
        self.posted_at = "2026-01-01"
        self.observed_at = "2026-01-03"


class WorldModel:
    """Reach-driven model: each post decays with the number before it."""

    def __init__(self):
        self.reports = []

    def initial_state(self):
        return {"day": 0, "phase": "operator", "posts": [], "last": None}

    def apply_action(self, state, action):
        nxt = {
            "day": state["day"],
            "phase": state["phase"],
            "posts": list(state["posts"]),
            "last": state["last"],
        }
        if nxt["phase"] == "operator":
            if action.startswith("publish"):
                nxt["posts"].append(action)
                nxt["last"] = action
            nxt["phase"] = "chance"
            return nxt
        nxt["day"] += 1
        nxt["phase"] = "terminal" if nxt["day"] >= HORIZON else "operator"
        return nxt

    def get_current_player(self, state):
        if state["phase"] == "terminal":
            return -4
        if state["phase"] == "chance":
            return -1
        return 0

    def get_legal_actions(self, state):
        if state["phase"] != "operator":
            return []
        return [
            "hold",
            "publish|tiktok|carousel|ugc_review|anger_injustice|tribal_identity|"
            "pattern_interrupt|avatar=solo_founder|cta=reply_keyword|"
            "claim=mechanism|angle=launch_theater|utm=v1stub01",
        ]

    def get_observations(self, state):
        if state["last"] is None:
            obs = Obs("", 0, 0.0, 0)
        else:
            index = state["posts"].index(state["last"])
            reach = 900.0 / (1.0 + index * 0.3)
            obs = Obs(state["last"].split("utm=")[-1], reach, 0.26, reach * 0.02)
        return {0: obs, 1: obs, 2: obs}

    def get_rewards(self, state):
        return {0: 0.0, 1: 0.0, 2: 0.0}

    def chance_outcomes(self, state):
        if state["phase"] != "chance":
            return []
        return [
            ("chance|response=low|drift=flat", 0.25),
            ("chance|response=mid|drift=flat", 0.50),
            ("chance|response=high|drift=flat", 0.25),
        ]
'''

V2_SOURCE = V1_SOURCE.replace(
    '            "hold",\n',
    '            "hold",\n'
    f'            "{ACTION_A}",\n'
    f'            "{ACTION_B}",\n',
)

INFERENCE_SOURCE = '''\
"""Candidate state sampler: belief centred on the observed history length."""


class StateInferenceSampler:
    def __init__(self):
        self.confidence = 0.5

    def resample_state(self, obs_action_history, player_id):
        seen = [pair for pair in obs_action_history if pair[0] is not None]
        return {
            "day": len(obs_action_history),
            "step": len(obs_action_history),
            "observed": len(seen),
            "theta": {"hook_rate": 1.1, "hold_rate": 0.9},
            "standing": 0.7,
            "saturation": {},
            "belief": {},
            "asset_fatigue": {},
        }
'''


def publish_a() -> Publish:
    return Publish(
        platform=Platform.TIKTOK,
        format=Format.CAROUSEL,
        archetype=Archetype.ANTI_HERO_RANT,
        vector=EmotionalVector.ANGER_INJUSTICE,
        semantic_tier=SemanticTier.TRIBAL_IDENTITY,
        hook=HookFamily.PATTERN_INTERRUPT,
        avatar="solo_founder",
        cta_mode=CtaMode.START_TRIAL,
        claim_class=ClaimClass.FIRST_PARTY_PROOF,
        angle="launch_theater",
        utm_content="c0412",
    )


def settled_observation(utm: str, reach: int) -> Observation:
    return Observation(
        utm_content=utm,
        posted_at="2026-01-01",
        observed_at="2026-01-04",
        impressions=reach * 2,
        reach=reach,
        hook_rate=0.26,
        hold_rate=0.19,
        saves=reach // 90,
        shares=reach // 120,
        comments=reach // 150,
        profile_visits=reach // 80,
        link_clicks=reach // 500,
        attributed_conversions=max(1, reach // 120),
        attribution_coverage=0.72,
        incrementality=0.77,
        is_partial=False,
        dark_social_estimate=0.65,
    )


def partial_observation(utm: str, reach: int) -> Observation:
    from dataclasses import replace

    return replace(
        settled_observation(utm, reach),
        attributed_conversions=reach // 400,
        is_partial=True,
    )


def make_trajectory() -> Trajectory:
    """Three days: a settled post, a post still inside the lag, a hold."""
    trajectory = Trajectory(account="test")
    trajectory.steps.append(
        Step(move=publish_a(), observation=settled_observation("c0412", 640))
    )
    second = Publish(
        platform=Platform.X,
        format=Format.TEXT_THREAD,
        archetype=Archetype.UGC_REVIEW,
        vector=EmotionalVector.ASPIRATION_STATUS,
        semantic_tier=SemanticTier.GENERIC_SLOP,
        hook=HookFamily.CURIOSITY_GAP,
        avatar="agency_ops",
        cta_mode=CtaMode.REPLY_KEYWORD,
        claim_class=ClaimClass.MECHANISM,
        angle="enemy_of_slop",
        utm_content="c07e33",
    )
    trajectory.steps.append(
        Step(move=second, observation=partial_observation("c07e33", 310))
    )
    trajectory.steps.append(Step(move=Hold(), observation=None))
    return trajectory


def fenced(source: str) -> str:
    return f"Here is the module:\n```python\n{source}```\nUse it wisely."


# ---------------------------------------------------------------------------
# Sandbox.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "source",
    [
        "import os",
        "import socket",
        "from os import path",
        "f = open('secrets.txt')",
        "eval('1 + 1')",
        "exec('x = 1')",
        "compile('x=1', 'x', 'exec')",
        "kids = object.__subclasses__()",
        "state.__globals__",
        "fn.__code__",
        "cls.__name__",
    ],
)
def test_sandbox_refuses_forbidden_constructs(source: str) -> None:
    with pytest.raises(SandboxViolation) as excinfo:
        Sandbox().load(source, SandboxConfig())
    message = str(excinfo.value)
    assert "line 1" in message, f"violation must name the line: {message}"


def test_sandbox_refusal_names_the_node() -> None:
    with pytest.raises(SandboxViolation) as excinfo:
        Sandbox().load("x = 1\nimport os\n", SandboxConfig())
    assert "line 2" in str(excinfo.value)
    assert "os" in str(excinfo.value)


def test_sandbox_executes_against_bound_values_not_modules() -> None:
    """Synthesised code gets values, never modules, and needs no imports.

    The previous version of this test imported `math`, `random` and
    `dataclasses` and asserted they worked. That was the vulnerability: an
    allowlist of modules is not a boundary, because module objects form a
    reachable graph and allowlisted ones re-export dangerous ones as ordinary
    non-dunder attributes: `random._os` is the real `os`. The names below are
    pre-bound values, so there is nothing to traverse.
    """
    source = (
        "@dataclass\n"
        "class Box:\n"
        "    value: float\n"
        "\n"
        "RESULT = Box(sqrt(16.0))\n"
        "DRAW = Random(1).random()\n"
    )
    namespace = Sandbox().load(source, SandboxConfig())
    assert namespace.RESULT.value == 4.0
    assert random.Random(1).random() == namespace.DRAW


def test_sandbox_namespace_contains_no_module_objects() -> None:
    """The invariant that closes the entire escape class.

    Every published bypass of the previous sandbox (`random._os`,
    `typing.sys.modules`, `dataclasses.builtins.open`, `collections._sys`,
    `json.codecs`) began by reaching a module object bound in the namespace.
    If nothing in the namespace is a module, none of them have a first step,
    and the property holds without enumerating the attacks.

    This assertion is worth more than the nine regression tests below it,
    because those cover the bypasses we know about and this covers the ones we
    do not.
    """
    namespace = Sandbox().load("VALUE = sqrt(9.0)\n", SandboxConfig())
    leaked = {
        name: type(value).__name__
        for name, value in vars(namespace).items()
        if isinstance(value, types.ModuleType)
    }
    assert leaked == {}, f"module objects reachable from sandbox namespace: {leaked}"


@pytest.mark.parametrize(
    "source",
    [
        "import random\nX = random._os.getcwd()\n",
        "from random import _os\nX = _os.getpid()\n",
        "import typing\nX = typing.sys.modules['os']\n",
        "import dataclasses\nX = dataclasses.builtins.open('/etc/hostname').read()\n",
        "import collections\nX = collections._sys.modules['os']\n",
        "import json\nX = json.codecs.open('/etc/hostname').read()\n",
        "import statistics\nX = statistics.random._os.getpid()\n",
        "import re\nX = re.enum\n",
        "import datetime\nX = datetime.sys.executable\n",
    ],
    ids=[
        "random._os",
        "from-random-import-_os",
        "typing.sys.modules",
        "dataclasses.builtins.open",
        "collections._sys",
        "json.codecs",
        "statistics.random",
        "re.enum",
        "datetime.sys",
    ],
)
def test_sandbox_refuses_known_module_graph_escapes(source: str) -> None:
    """Every one of these executed successfully against the previous sandbox.

    They are recorded here as regressions rather than as a security boundary:
    the boundary is the no-modules invariant above. Note that none of them use
    a forbidden attribute name, which is why a longer denylist would not have
    helped.
    """
    with pytest.raises(SandboxViolation):
        Sandbox().load(source, SandboxConfig())


def test_sandbox_load_applies_the_timeout() -> None:
    """A module-level infinite loop must raise, not hang.

    `timeout_seconds` was previously read by nothing: `load` ran a bare `exec`,
    so one synthesised module with a top-level loop would wedge a 500-call
    refinement run forever.
    """
    with pytest.raises(SandboxTimeout):
        Sandbox().load("while True:\n    pass\n", SandboxConfig(timeout_seconds=1.0))


def test_sandbox_timeout_raises() -> None:
    namespace = Sandbox().load(
        "def slow():\n"
        "    total = 0\n"
        "    for i in range(10 ** 12):\n"
        "        total += i\n"
        "    return total\n",
        SandboxConfig(),
    )
    with pytest.raises(SandboxTimeout):
        call_with_timeout(namespace.slow, (), timeout=0.25)


def test_call_with_timeout_returns_the_value() -> None:
    def add(a: int, b: int) -> int:
        return a + b

    assert call_with_timeout(add, (20, 22), timeout=5.0) == 42


def test_protocol_violation_lists_every_missing_method() -> None:
    source = "class WorldModel:\n    def initial_state(self):\n        return {}\n"
    namespace = Sandbox().load(source, SandboxConfig())
    with pytest.raises(ProtocolViolation) as excinfo:
        instantiate(namespace, "WorldModel")
    message = str(excinfo.value)
    for missing in (
        "apply_action",
        "get_current_player",
        "get_legal_actions",
        "get_observations",
        "get_rewards",
        "chance_outcomes",
    ):
        assert missing in message, f"must list {missing}: {message}"


def test_protocol_violation_on_missing_class() -> None:
    namespace = Sandbox().load("X = 1\n", SandboxConfig())
    with pytest.raises(ProtocolViolation, match="not found"):
        instantiate(namespace, "WorldModel")


# ---------------------------------------------------------------------------
# Reference world model.
# ---------------------------------------------------------------------------


def reference_model() -> ReferenceWorldModel:
    return ReferenceWorldModel(ReferenceConfig(horizon=6))


def first_publish_policy(model: CodeWorldModel, state: dict) -> str:
    for action in model.get_legal_actions(state):
        if action.startswith("publish"):
            return action
    return model.get_legal_actions(state)[0]


def run_episode(model: CodeWorldModel, policy, rng: random.Random) -> dict:
    state = model.initial_state()
    plies = 0
    while model.get_current_player(state) != TERMINAL_PLAYER and plies < 200:
        player = model.get_current_player(state)
        if player == -1:
            outcomes = model.chance_outcomes(state)
            action = rng.choices(
                [k for k, _ in outcomes], weights=[p for _, p in outcomes], k=1
            )[0]
        else:
            action = policy(model, state)
        state = model.apply_action(state, action)
        plies += 1
    return state


def test_reference_satisfies_protocol_structurally() -> None:
    model = reference_model()
    assert isinstance(model, CodeWorldModel)
    assert check_protocol_methods(model, CWM_METHOD_PARAMS, "Reference") == []


def test_reference_runs_a_full_episode_to_terminal() -> None:
    model = reference_model()
    state = run_episode(model, first_publish_policy, random.Random(5))
    assert model.get_current_player(state) == TERMINAL_PLAYER
    assert state["log"], "publishing every day must produce observations"
    rewards = model.get_rewards(state)
    assert all(isinstance(v, float) for v in rewards.values())


def test_reference_transitions_are_deterministic() -> None:
    model = reference_model()
    state_a = run_episode(model, first_publish_policy, random.Random(9))
    state_b = run_episode(model, first_publish_policy, random.Random(9))
    assert state_a["log"] == state_b["log"]


def test_reference_apply_action_does_not_mutate() -> None:
    model = reference_model()
    state = model.initial_state()
    action = first_publish_policy(model, state)
    before = repr(sorted(state.items(), key=lambda kv: kv[0]))
    successor = model.apply_action(state, action)
    assert successor is not state
    assert repr(sorted(state.items(), key=lambda kv: kv[0])) == before


def test_reference_observations_never_leak_hidden_state() -> None:
    model = reference_model()
    state = run_episode(model, first_publish_policy, random.Random(4))
    hidden_keys = {"theta", "standing", "saturation", "belief", "asset_fatigue"}
    observations = model.get_observations(state)
    for player, obs in observations.items():
        fields = set(obs.__dataclass_fields__)
        leaked = fields & hidden_keys
        assert not leaked, f"player {player} observation leaks {leaked}"
        serialised = {k: str(v) for k, v in asdict(obs).items()}
        for key in hidden_keys:
            assert key not in serialised
            assert all(key not in v for v in serialised.values())


def test_generate_trajectory_attaches_observations() -> None:
    model = reference_model()
    trajectory = model.generate_trajectory(first_publish_policy, 6, random.Random(2))
    assert len(trajectory.steps) == 6
    assert all(isinstance(step.move, (Publish, Hold)) for step in trajectory.steps)
    attached = [s for s in trajectory.steps if s.observation is not None]
    assert attached, "a six-day posting policy must attach observations"
    # The last post or two are still inside the 24-72h reporting window when the
    # episode ends, so their observations are legitimately provisional. What
    # matters is that a provisional one is labelled, not that none exists:
    # test generation drops them on the flag, and an unflagged provisional
    # number is the thing that would poison the training signal.
    assert any(not s.observation.is_partial for s in attached)
    settled = [s for s in attached if not s.observation.is_partial]
    assert len(settled) >= len(attached) - 3


# ---------------------------------------------------------------------------
# Tests from trajectories.
# ---------------------------------------------------------------------------


def test_partial_observations_never_become_test_cases() -> None:
    tests = generate(make_trajectory(), include_hidden=True)
    names = [t.name for t in tests]
    assert not any("1]" in name for name in names), (
        f"step 1 is partial and must not be a test: {names}"
    )
    for test in tests:
        payload = str(test.payload)
        assert "c07e33" not in payload or test.name.startswith("no_crash"), (
            "the partial observation's utm must not appear in any test"
        )


def test_closed_deck_default_emits_only_reconstruction_and_no_crash() -> None:
    tests = generate(make_trajectory(), include_hidden=False)
    kinds = {t.kind for t in tests}
    assert kinds == {OBSERVATION_RECONSTRUCTION, NO_CRASH}


def test_open_deck_adds_hidden_state_tests() -> None:
    tests = generate(make_trajectory(), include_hidden=True)
    kinds = {t.kind for t in tests}
    assert kinds == {
        TRANSITION,
        LEGALITY,
        OBSERVATION_RECONSTRUCTION,
        NO_CRASH,
        TERMINATION,
    }


def test_tolerance_separates_counts_from_rates() -> None:
    tolerance = Tolerance()
    # Defaults are counts 0.05, rates 0.02. They were 0.25 and 0.10 while
    # replay re-sampled chance, and had to be that wide to absorb a bucket the
    # model could not predict; with chance replayed the slack is unnecessary.
    assert not tolerance.allows("reach", 1350, 1000)
    assert not tolerance.allows("reach", 1150, 1000)
    # 4% off a count is fine; 4% off a rate is not.
    assert tolerance.allows("reach", 1040, 1000)
    assert not tolerance.allows("hook_rate", 0.104, 0.100)
    assert tolerance.allows("hook_rate", 0.1015, 0.100)
    # A zero actual must not demand an exactly-zero prediction: the floor of
    # one unit buys small noise around zero, and nothing more.
    assert tolerance.allows("reach", 0.04, 0)
    assert not tolerance.allows("reach", 2, 0)


def test_split_is_deterministic_disjoint_and_complete() -> None:
    tests = generate(make_trajectory(), include_hidden=True)
    train_a, test_a = split(tests, 0.7, seed=99)
    train_b, test_b = split(tests, 0.7, seed=99)
    assert [t.name for t in train_a] == [t.name for t in train_b]
    assert [t.name for t in test_a] == [t.name for t in test_b]
    assert len(train_a) + len(test_a) == len(tests)
    assert not {t.name for t in train_a} & {t.name for t in test_a}


def test_no_crash_test_passes_on_a_working_model() -> None:
    namespace = Sandbox().load(V1_SOURCE, SandboxConfig())
    model = instantiate(namespace, "WorldModel")
    test = ModelTest(name="no_crash", kind=NO_CRASH, payload={"steps": 8, "seed": 3})
    assert test.run(model).passed


def test_reconstruction_test_catches_an_out_of_tolerance_prediction() -> None:
    namespace = Sandbox().load(V1_SOURCE, SandboxConfig())
    model = instantiate(namespace, "WorldModel")
    # V1 predicts reach 900 for the first post; the recording says 640,
    # which is outside the 0.25 count band (|900-640| = 260 > 160).
    test = ModelTest(
        name="reconstruction[0]",
        kind=OBSERVATION_RECONSTRUCTION,
        payload={
            "actions": [ACTION_A],
            "expected": {
                "utm_content": "c0412",
                "metrics": {"reach": 640.0, "hook_rate": 0.26},
            },
            "seed": 0,
        },
        tolerance=Tolerance(),
    )
    result = test.run(model)
    assert not result.passed
    assert "reach" in result.detail


# ---------------------------------------------------------------------------
# LLM client plumbing.
# ---------------------------------------------------------------------------


class _ScriptedClient:
    def __init__(self, responses: list[str]) -> None:
        self._responses = list(responses)

    def complete(self, system: str, user: str, stop: list[str] | None = None):
        return self._responses.pop(0)


def test_recorded_client_replays_and_misses(tmp_path: Path) -> None:
    fixture = tmp_path / "fixture.jsonl"
    inner = _ScriptedClient(["first response"])
    recording = RecordingClient(inner, fixture)
    assert recording.complete("sys", "usr") == "first response"

    replay_client = RecordedClient(fixture)
    assert replay_client.complete("sys", "usr") == "first response"
    with pytest.raises(FixtureMiss) as excinfo:
        replay_client.complete("sys", "different")
    assert excinfo.value.key == prompt_key("sys", "different")


def test_extract_code_handles_fences_and_prose() -> None:
    assert extract_code("```python\nx = 1\n```") == "x = 1"
    assert extract_code("no fence at all\nx = 1") == "no fence at all\nx = 1"
    two_blocks = "```python\nx = 1\n```\nthoughts\n```python\ny = 2\nz = 3\n```"
    assert extract_code(two_blocks) == "y = 2\nz = 3"


def test_build_prompt_carries_rules_api_trajectories_and_error() -> None:
    trajectory = make_trajectory()
    system, user = build_prompt(RULES_TEXT, [trajectory], None, None)
    assert "distribution" in system
    assert RULES_TEXT.strip() in user
    assert "def initial_state" in user, "the required API is the regulariser"
    assert "utm=c0412" in user
    assert "PREVIOUS ATTEMPT" not in user

    _, refinement_user = build_prompt(
        RULES_TEXT, [trajectory], None, "Traceback ... Error: bad model"
    )
    assert "PREVIOUS ATTEMPT FAILED" in refinement_user
    assert "Traceback ... Error: bad model" in refinement_user


def test_synthesise_produces_one_candidate_from_fixture() -> None:
    client = RecordedClient(FIXTURES / "synthesis_world_model.jsonl")
    tests = [
        ModelTest(name="no_crash", kind=NO_CRASH, payload={"steps": 8, "seed": 3})
    ]
    result = synthesise(
        client, SynthConfig(), RULES_TEXT, [make_trajectory()], tests
    )
    assert result.model is not None, result.error
    assert result.llm_calls == 1
    assert result.passed == 1
    assert result.total == 1
    assert result.pass_rate == 1.0


# ---------------------------------------------------------------------------
# Refinement.
# ---------------------------------------------------------------------------


class _CapturingRandom(random.Random):
    """Records every (alpha, beta) handed to betavariate."""

    def __init__(self, seed: int) -> None:
        super().__init__(seed)
        self.draws: list[tuple[float, float]] = []

    def betavariate(self, alpha: float, beta: float) -> float:
        self.draws.append((alpha, beta))
        return super().betavariate(alpha, beta)


def test_beta_selection_uses_the_papers_exact_alpha_beta() -> None:
    tree = RefinementTree(
        nodes=[
            RefinementNode("high", 0.8),
            RefinementNode("low", 0.2),
        ],
        heuristic_weight=5.0,
    )
    rng = _CapturingRandom(7)
    tree.select(rng)
    assert rng.draws[0] == pytest.approx((1.0 + 5.0 * 0.8, 1.0 + 0.2 * 5.0))
    assert rng.draws[0] == pytest.approx((5.0, 2.0))
    assert rng.draws[1] == pytest.approx((1.0 + 5.0 * 0.2, 1.0 + 0.8 * 5.0))
    assert rng.draws[1] == pytest.approx((2.0, 5.0))


def test_beta_selection_favours_the_high_h_node() -> None:
    tree = RefinementTree(
        nodes=[RefinementNode("good", 0.9), RefinementNode("bad", 0.1)]
    )
    rng = random.Random(21)
    wins = sum(1 for _ in range(1000) if tree.select(rng).source == "good")
    assert wins > 900, f"high-h node should dominate; won {wins}/1000"


def test_refinement_stops_early_at_pass_rate_one() -> None:
    namespace = Sandbox().load(V1_SOURCE, SandboxConfig())
    root_model = instantiate(namespace, "WorldModel")
    root = RefinementNode(source=V1_SOURCE, h=0.0, model=root_model)
    tree = RefinementTree(
        nodes=[root],
        rules_text=RULES_TEXT,
        trajectories=[make_trajectory()],
        heuristic_weight=5.0,
    )
    legality_a = ModelTest(
        name="legality[0]",
        kind=LEGALITY,
        payload={"prefix": [], "action": ACTION_A, "seed": 0},
    )
    legality_b = ModelTest(
        name="legality[1]",
        kind=LEGALITY,
        payload={"prefix": [ACTION_A], "action": ACTION_B, "seed": 1},
    )
    # The root model omits both recorded actions from its legal set, so both
    # tests fail and prompt a refinement. The fixture holds exactly one
    # response: if refine did not stop at the perfect child it would ask for
    # a second and RecordedClient would raise FixtureMiss.
    client = RecordedClient(FIXTURES / "refinement_pass.jsonl")
    config = RefineConfig(num_retries=500)
    refined = refine_tree(client, tree, [legality_a, legality_b], config)

    assert len(refined.nodes) == 2
    winner = refined.nodes[1]
    assert winner.h == 1.0
    assert winner.parent is root
    assert root.refinements == 1


# ---------------------------------------------------------------------------
# Inference.
# ---------------------------------------------------------------------------


def test_state_inference_synthesises_from_fixture() -> None:
    client = RecordedClient(FIXTURES / "state_inference.jsonl")
    inference = synthesise_state_inference(
        client, SynthConfig(), RULES_TEXT, [make_trajectory()]
    )
    state = inference.resample_state([(None, ACTION_A)], 0)
    assert isinstance(state, dict)
    assert "theta" in state


def test_state_inference_source_persists_and_reloads() -> None:
    """The synth -> plan handoff: what ``fronts synth`` writes to disk,
    ``fronts plan`` must read back as the same working sampler."""
    client = RecordedClient(FIXTURES / "state_inference.jsonl")
    source = synthesise_state_inference_source(
        client, SynthConfig(), RULES_TEXT, [make_trajectory()]
    )
    assert source is not None
    sampler = load_state_inference(source)
    assert sampler is not None
    state = sampler.resample_state([(None, ACTION_A)], 0)
    assert isinstance(state, dict)
    assert "theta" in state


def test_load_state_inference_round_trips_and_rejects() -> None:
    sampler = load_state_inference(INFERENCE_SOURCE)
    assert sampler is not None
    assert sampler.resample_state([], 0)["theta"]["hook_rate"] == 1.1
    assert load_state_inference("x = 1\n") is None, (
        "source without the sampler class must not load"
    )


def test_state_inference_falls_back_when_synthesis_fails() -> None:
    # The synthesis fixture cannot answer the inference prompt, so the
    # sampler degrades to the fallback instead of raising.
    client = RecordedClient(FIXTURES / "synthesis_world_model.jsonl")
    inference = synthesise_state_inference(
        client, SynthConfig(), RULES_TEXT, [make_trajectory()]
    )
    assert isinstance(inference, FallbackInference)
    assert inference.resample_state([], 0) == {}


def test_fallback_inference_returns_the_models_initial_state() -> None:
    model = reference_model()
    fallback = FallbackInference(model=model)
    assert fallback.resample_state([], 0) == model.initial_state()
    assert fallback.resample_history([], 0) == []


def rotating_publish_policy(model: CodeWorldModel, state: dict) -> str:
    """Publish a different item each day, so every post carries a unique
    utm, the realistic case, since utm_content is the join key between a
    move and its observation."""
    publishes = [
        action
        for action in model.get_legal_actions(state)
        if action.startswith("publish")
    ]
    if not publishes:
        return model.get_legal_actions(state)[0]
    return publishes[state.get("hidden", {}).get("step", 0) % len(publishes)]


def test_validate_history_accepts_consistent_and_rejects_contradicted() -> None:
    model = reference_model()
    trajectory = model.generate_trajectory(
        rotating_publish_policy, 6, random.Random(11)
    )
    actions = [ActionCodec().encode(step.move) for step in trajectory.steps]
    # Replay the recorded chance sequence, not a fresh seed-0 draw. Sampling
    # here would compare the model against a branch that never happened, which
    # is the defect that made transition tests unmeasurable.
    observations = []
    for index in range(len(actions)):
        state = replay(model, actions[: index + 1], seed=0, chance=trajectory.chance)
        obs = model.get_observations(state)[0]
        if obs.utm_content:
            observations.append(obs)
    assert len({obs.utm_content for obs in observations}) == len(observations), (
        "each post must have its own utm for validation to be well-posed"
    )
    assert validate_history(model, actions, observations, trajectory.chance)

    from dataclasses import replace

    # Contradict a settled observation. Provisional ones are skipped by design:
    # a number still inside the reporting window cannot contradict anything,
    # because it is not yet a claim about what happened. Falsifying a partial
    # observation and expecting rejection tests the skip, not the validator.
    settled = next(obs for obs in observations if not obs.is_partial)
    contradicted = [replace(settled, reach=settled.reach * 50)]
    assert not validate_history(model, actions, contradicted, trajectory.chance)


# ---------------------------------------------------------------------------
# Arena.
# ---------------------------------------------------------------------------


def hold_policy(model: CodeWorldModel, state: dict) -> str:
    legal = model.get_legal_actions(state)
    for action in legal:
        if action == "hold":
            return action
    return legal[0]


def service_policy(model: CodeWorldModel, state: dict) -> str:
    for action in model.get_legal_actions(state):
        if action.startswith("publish") and "cta=reply_keyword" in action:
            return action
    return first_publish_policy(model, state)


def test_play_episode_is_seeded_and_deterministic() -> None:
    model = reference_model()
    a = play_episode(model, first_publish_policy, seed=123)
    b = play_episode(model, first_publish_policy, seed=123)
    assert a == b
    assert a != play_episode(model, hold_policy, seed=123)


def test_arena_rejects_the_loser_and_keeps_the_winner() -> None:
    model = ReferenceWorldModel(ReferenceConfig(horizon=10))
    agents = [first_publish_policy, service_policy, hold_policy]
    result = arena_run([model], agents, ArenaConfig(matches_per_pairing=3))
    # The rule, verbatim: reject any agent "worse than the best scoring
    # agent by more than 10% of the observed utility range."
    best = max(result.scores)
    threshold = 0.10 * result.utility_range
    for index in result.rejected:
        assert best - result.scores[index] > threshold
    for index in result.survivors:
        assert best - result.scores[index] <= threshold
    assert set(result.survivors) | set(result.rejected) == {0, 1, 2}
    assert result.survivors, "at least one agent must survive"
    assert 2 in result.rejected, "the hold-everything agent must be rejected"
    assert 0 in result.survivors or 1 in result.survivors


# ---------------------------------------------------------------------------
# Report.
# ---------------------------------------------------------------------------


def test_report_formats_train_test_and_online() -> None:
    report = ModelQualityReport(
        transition_accuracy_train=0.78,
        transition_accuracy_test=0.75,
        transition_accuracy_online=0.71,
        inference_accuracy_train=0.81,
        inference_accuracy_test=0.77,
        inference_accuracy_online=0.70,
        llm_calls=500,
        passed_tests=39,
        total_tests=52,
    )
    table = report.format_table()
    for section in ("train", "test", "online"):
        assert section in table
    assert "0.78" in table and "0.75" in table and "0.71" in table
    assert "transition" in table and "inference" in table
    assert "500" in table
    # The protocol's headline properties expose the held-out split.
    assert report.transition_accuracy == 0.75
    assert report.inference_accuracy == 0.77
    assert report.llm_calls == 500
    assert (report.passed_tests, report.total_tests) == (39, 52)


def test_report_renders_unmeasured_inference_as_na() -> None:
    """The default is None (not measured) and the table must say so
    rather than manufacture a number (``fronts accuracy`` relies on this)."""
    report = ModelQualityReport(
        transition_accuracy_train=0.9,
        transition_accuracy_test=0.8,
        transition_accuracy_online=0.7,
    )
    table = report.format_table()
    assert table.count("n/a") == 3
    assert report.inference_accuracy is None


def _random_policy(model: object, state: object) -> str:
    legal = model.get_legal_actions(state)  # type: ignore[attr-defined]
    return random.Random(len(str(state))).choice(legal) if legal else "hold"


@pytest.mark.parametrize("horizon", [10, 20, 30])
@pytest.mark.parametrize("include_hidden", [False, True], ids=["closed_deck", "open_deck"])
def test_reference_model_scores_one_against_its_own_trajectories(
    horizon: int, include_hidden: bool
) -> None:
    """The measurement instrument must read zero on a known-zero input.

    This is the most important test in the repository, and its absence let two
    defects live behind confident docstrings for the whole first draft.

    A model tested against trajectories it generated should score a perfect
    pass rate. Anything less means the harness is charging the model for
    something other than being wrong, and every downstream number inherits the
    error: refinement can never reach its early stop, so every run burns the
    full call budget, and accuracy reports sit on a scale whose maximum nobody
    knows. When this suite first ran, the reference model scored 0.20.

    Two causes, both bookkeeping rather than modelling:

    1. Replay re-sampled the chance player instead of replaying the recorded
       outcome, so a prediction made under one branch was compared against a
       recording made under another and the difference scored as model error.
    2. `generate_trajectory` let two distinct posts share a utm, and utm is the
       join key between a move and its observation. The later post's metrics
       overwrote the earlier's, which read as a 3x prediction error.

    Note the tolerances are the tightened ones: counts 0.05, rates 0.02. The
    original 0.25/0.10 existed to absorb a +/-50% chance bucket the model could
    not predict, which is a tolerance concealing a broken measurement rather
    than accommodating real variance.
    """
    config = ReferenceConfig(horizon=horizon, seed=7)
    recorder = ReferenceWorldModel(config)
    trajectory = recorder.generate_trajectory(_random_policy, horizon, random.Random(7))

    tests = generate(trajectory, Tolerance(), include_hidden=include_hidden)
    assert tests, "a trajectory of this length must yield tests"

    subject = ReferenceWorldModel(config)
    results = [test.run(subject) for test in tests]
    failures = [r.detail for r in results if not r.passed]
    assert not failures, (
        f"ground truth failed {len(failures)}/{len(results)} of its own tests; "
        f"the harness is measuring something other than model error: {failures[:3]}"
    )


def test_trajectory_records_chance_outcomes() -> None:
    """Without the recorded chance sequence the test above cannot hold.

    Transitions are deterministic given the chance action, so a recording that
    discards it cannot be replayed, only re-rolled.
    """
    config = ReferenceConfig(horizon=12, seed=3)
    model = ReferenceWorldModel(config)
    trajectory = model.generate_trajectory(_random_policy, 12, random.Random(3))
    assert trajectory.chance, "chance outcomes must be recorded, not discarded"
    assert all(isinstance(key, str) for key in trajectory.chance)


def test_generated_trajectory_utms_are_unique() -> None:
    """utm is the join key between a move and its observation, so a collision
    silently merges two posts into one row."""
    config = ReferenceConfig(horizon=30, seed=11)
    model = ReferenceWorldModel(config)
    trajectory = model.generate_trajectory(_random_policy, 30, random.Random(11))
    utms = [
        step.move.utm_content
        for step in trajectory.steps
        if isinstance(step.move, Publish)
    ]
    assert len(utms) == len(set(utms)), "duplicate utm_content across distinct posts"


def test_inference_accuracy_scores_an_oracle_at_one() -> None:
    """A perfect sampler must be able to score 1.0.

    It could not before. Dispatch sniffed for a `resample_history` attribute,
    so any sampler defining both methods (`FallbackInference` among them)
    went down the history path, where an empty sample failed validation on the
    first comparison. The function returned 0.0 for every input it was ever
    given, was exported, and had no test.
    """
    config = ReferenceConfig(horizon=15, seed=4)
    model = ReferenceWorldModel(config)
    trajectory = model.generate_trajectory(_random_policy, 15, random.Random(4))
    actions = [ActionCodec().encode(step.move) for step in trajectory.steps]

    class Oracle:
        """Reconstructs the true state by replaying the recorded history."""

        def resample_state(self, history: list, player_id: int) -> dict:
            return replay(model, actions[: len(history) + 1], 0, trajectory.chance)

        def resample_history(self, history: list, player_id: int) -> list:
            return actions[: len(history) + 1]

    assert inference_accuracy(model, Oracle(), [trajectory], mode="state") == 1.0
    assert inference_accuracy(model, Oracle(), [trajectory], mode="history") == 1.0

    # The fallback should score low by measurement, not by being
    # structurally unable to score at all.
    fallback = inference_accuracy(
        model, FallbackInference(model=model), [trajectory], mode="state"
    )
    assert 0.0 <= fallback < 0.5


def test_inference_accuracy_rejects_an_unknown_mode() -> None:
    model = ReferenceWorldModel(ReferenceConfig(horizon=6, seed=1))
    with pytest.raises(ValueError):
        inference_accuracy(model, FallbackInference(model=model), [], mode="sniff")


def test_inference_accuracy_counts_a_raising_sampler_as_misses() -> None:
    """The module contract is fall back, never propagate: a sampler that
    cannot be asked reads as a bad score, not a stack trace out of
    ``fronts accuracy``."""

    class Hostile:
        def resample_state(self, history: list, player_id: int) -> dict:
            raise RuntimeError("boom")

        def resample_history(self, history: list, player_id: int) -> list:
            raise RuntimeError("boom")

    config = ReferenceConfig(horizon=8, seed=2)
    model = ReferenceWorldModel(config)
    trajectory = model.generate_trajectory(_random_policy, 8, random.Random(2))
    assert inference_accuracy(model, Hostile(), [trajectory], mode="state") == 0.0
    assert inference_accuracy(model, Hostile(), [trajectory], mode="history") == 0.0


def test_load_state_inference_guards_the_sampler(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The persisted sampler came off disk and is untrusted: the loader must
    wrap ``resample_state`` in the timeout guard, so a spinning sampler costs
    the planner one skipped determinization, never the whole run."""
    import fronts.cwm.inference as inference_module

    seen: dict[str, object] = {}
    real_guard = inference_module.guard_methods

    def spy(obj: object, names: object, timeout: float) -> object:
        seen["names"] = tuple(names)  # type: ignore[arg-type]
        seen["timeout"] = timeout
        return real_guard(obj, names, timeout)  # type: ignore[arg-type]

    monkeypatch.setattr(inference_module, "guard_methods", spy)
    sampler = load_state_inference(INFERENCE_SOURCE, timeout_seconds=2.0)
    assert sampler is not None
    assert seen == {"names": ("resample_state",), "timeout": 2.0}
    # The guard forwards a healthy call unchanged.
    assert sampler.resample_state([], 0)["theta"]["hook_rate"] == 1.1


@pytest.mark.parametrize("horizon", [6, 10, 11, 20, 21])
def test_validate_history_accepts_a_model_validating_itself(horizon: int) -> None:
    """Horizon-independent, which it was not.

    The replay loop broke on the action list at the top, so after the last
    operator move the following chance ply never ran and the final publish never
    resolved into an observation. The result was True at 6, False at 10, True at
    20, which reads exactly like a horizon-dependent modelling weakness and is
    an off-by-one. The original test used horizon 6 and passed by luck.
    """
    config = ReferenceConfig(horizon=horizon, seed=5)
    model = ReferenceWorldModel(config)
    trajectory = model.generate_trajectory(_random_policy, horizon, random.Random(5))
    actions = [ActionCodec().encode(step.move) for step in trajectory.steps]
    observations = [s.observation for s in trajectory.steps if s.observation is not None]

    subject = ReferenceWorldModel(config)
    assert validate_history(subject, actions, observations, trajectory.chance)
